/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#e0e0ff",
        "outline": "#767683",
        "surface-container": "#f0eded",
        "background": "#fbf9f8",
        "on-background": "#1b1c1c",
        "inverse-surface": "#303030",
        "secondary": "#705d00",
        "on-error": "#ffffff",
        "on-secondary-container": "#6f5c00",
        "primary-fixed-dim": "#bdc2ff",
        "surface-dim": "#dcd9d9",
        "surface-tint": "#4c56af",
        "primary": "#000666",
        "secondary-fixed-dim": "#e9c400",
        "on-primary-fixed": "#000767",
        "surface-container-low": "#f5f3f3",
        "surface-container-high": "#eae8e7",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#f2f0f0",
        "on-secondary": "#ffffff",
        "on-surface": "#1b1c1c",
        "surface": "#fbf9f8",
        "on-tertiary-fixed-variant": "#374951",
        "on-primary-container": "#8690ee",
        "outline-variant": "#c6c5d4",
        "error": "#ba1a1a",
        "surface-container-highest": "#e4e2e1",
        "on-secondary-fixed": "#221b00",
        "error-container": "#ffdad6",
        "inverse-primary": "#bdc2ff",
        "tertiary": "#0a1d24",
        "on-surface-variant": "#454652",
        "on-tertiary": "#ffffff",
        "primary-container": "#1a237e",
        "surface-variant": "#e4e2e1",
        "on-secondary-fixed-variant": "#544600",
        "on-tertiary-container": "#879aa2",
        "secondary-container": "#fdd400",
        "tertiary-container": "#203239",
        "tertiary-fixed-dim": "#b6cad2",
        "surface-bright": "#fbf9f8",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#343d96",
        "secondary-fixed": "#ffe170",
        "tertiary-fixed": "#d2e6ef",
        "on-tertiary-fixed": "#0b1e24",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "12px",
        base: "8px",
        "container-max": "1200px",
        gutter: "24px",
        xl: "80px",
        lg: "48px",
        md: "24px",
      },
      fontFamily: {
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Source Sans 3", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-bold": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Source Sans 3", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "label-bold": ["14px", { lineHeight: "20px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
      },
      maxWidth: {
        "container-max": "1200px",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
